### ISSUE TITLE
Has this extension got any traction yet? 16 days since last created post!

### ISSUE THREAD

**Issue by corkiejp** [joneslloyd/bluniversal-comments#10]
Has this extension got any traction yet?

Last created post on : - https://bsky.app/profile/bluniversal.bsky.social
is from 16 days ago?

Can't seem to start a conversation with the extension?  It just opens a blank window after creating post,

Followed instructions and chrome was already in DEV mode. Have I to load some keys for it to work?

Regards
John

**Comment by joneslloyd** [comment]
> Has this extension got any traction yet?

Not so far!

> Last created post on : - https://bsky.app/profile/bluniversal.bsky.social

That's accurate, yes.

> Followed instructions and chrome was already in DEV mode. Have I to load some keys for it to work?

No, but I found an issue and have patched it.

The dev version will currently work as intended (instructions [here](https://github.com/joneslloyd/bluniversal-comments?tab=readme-ov-file#latest-unstable-version)), or wait a few days for the Chrome Web Store to get the latest version.
