### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by aurelg** [joneslloyd/bluniversal-comments#4]
Very neat idea! Any chance this could work with Firefox as well? 🙏

**Comment by aurelg** [comment]
Not an expert. :no_mouth: Here's what I did:

- created a clean temporary Firefox profile
- went to `about:debugging`
- clicked on `This firefox` then,
- clicked on `Load temporary add-on`

When I selected the file `chrome-extension.zip`, I have an error message: `background.service_worker is currently disabled`.

It's probably not what I expected, but it might be my fault?

**Comment by joneslloyd** [comment]
Oh thanks for this!

I think it's due to [this](https://stackoverflow.com/a/75203925).

TL;DR I will create two manifests – One for Firefox and one for Chrome.

**Comment by slrgt** [comment]
thank you! im excited to try this too

**Comment by joneslloyd** [comment]
[Firefox is now available](https://github.com/joneslloyd/bluniversal-comments?tab=readme-ov-file#firefox) :)
