### ISSUE TITLE
Error installing on Arc

### ISSUE THREAD

**Issue by Emilien-Valain** [joneslloyd/bluniversal-comments#7]
I've got several error while installing v0.0.025 : 

Context : background.js

Amplitude Logger [Error]: Failed to set cookie for key: AMP_TEST. Error: Cannot set properties of undefined (setting 'cookie')

Amplitude Logger [Error]: Failed to set cookie for key: AMP_MKTG_3f5227f9da. Error: Cannot set properties of undefined (setting 'cookie')

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'pushState')

**Comment by joneslloyd** [comment]
Fixed! Thanks for flagging.
