### ISSUE TITLE
Getting error: Failed to initialize the post. Please try again.

### ISSUE THREAD

**Issue by adamatic-me** [joneslloyd/bluniversal-comments#8]
I followed the steps to install, set username and password.

I then went to my testing URL and got this error in popup: Failed to initialize the post. Please try again.

url: https://www.nytimes.com/2024/11/22/technology/bluesky-x-alternative.html

![image](https://github.com/user-attachments/assets/93b56b1a-414a-4b54-b9ad-0cb8e4bc56b9)

**Comment by adamatic-me** [comment]
I tried later, and I did not get the error. hmm.

**Comment by joneslloyd** [comment]
This should be fixed now!
