### ISSUE TITLE
frontpage support?

### ISSUE THREAD

**Issue by slrgt** [joneslloyd/bluniversal-comments#9]
Will this also support comments posted on https://frontpage.fyi? It also uses the AtProtocol

**Comment by joneslloyd** [comment]
It would only work with frontpage.fyi if there were unique frontpage-specific URLs generated for each post.

I'm a fan of https://frontpage.fyi/ btw!

**Comment by joneslloyd** [comment]
I see what you mean.

That is not the direction that I'd like to take Bluniversal Comments in.

I think it'd work well with frontpage.fyi per my original comment, namely:

For each of your articles you have a frontpage URL (eg, https://frontpage.fyi/post/laurenshof.online/3lc3q6g7lgg2k) – Bluniversal Comments can be used for comments via the web browser extension.

I realise that this effectively competes with your own comments section though.
